site_name: BRational
site_author: Joshua Maglione
copyright: "&copy; 2024&ndash;2025 J. Maglione"
nav:
    - Home: index.md
    - brat: brat.md
    - Methods (brat): brat-methods.md
theme:
    name: mkdocs
    custom_dir: custom_theme/
