site_name: BRational Documentation
site_author: Joshua Maglione
copyright: "&copy; 2024 J. Maglione"
nav:
    - Home: index.md
    - brat: brat.md
theme:
    name: mkdocs
    custom_dir: custom_theme/
